export const UNDERLYING_FX_CCYPAIR_ADD = "UNDERLYING_FX_CCYPAIR_ADD";
export const UNDERLYING_FX_CCYPAIR_REMOVE = "UNDERLYING_FX_CCYPAIR_REMOVE";
export const UNDERLYING_FX_UPDATE = "UNDERLYING_FX_UPDATE";
